server:
  port: 8083
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: SUPPLIER-SERVICE
        uri: lb://SUPPLIER-SERVICE
        predicates:
        - Path=/supplier/**  
      - id: CUSTOMER-SERVICE
        uri: lb://CUSTOMER-SERVICE
        predicates:
        - Path=/customer/** 
      - id: TRANSPORTATION-SERVICE
        uri: lb://TRANSPORTATION-SERVICE
        predicates:
        - Path=/transportation/**
      - id: PURCHASE-SERVICE
        uri: lb://PURCHASE-SERVICE
        predicates:
        - Path=/purchase/** 
      - id: PRODUCTUNIT-SERVICE
        uri: lb://PRODUCTUNIT-SERVICE
        predicates:
        - Path=/unit/**   
          