server:
  port: 8083
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: MANDI-SERVICE
        uri: lb://MANDI-SERVICE
        predicates:
        - Path=/mandi/**  
      - id: PARTY-CUSTOMER
        uri: lb://PARTY-CUSTOMER
        predicates:
        - Path=/customer/** 
      - id: INVENTORY-SALES
        uri: lb://INVENTORY-SALES
        predicates:
        - Path=/order/**
      - id: INVENTORY-PURCHASE
        uri: lb://INVENTORY-PURCHASE
        predicates:
        - Path=/purchase/** 
      - id: INVENTORY-STOCK
        uri: lb://INVENTORY-STOCK
        predicates:
        - Path=/**   
          